### ISSUE TITLE
Error: Unknown RDF attribute: rdf:value

### ISSUE THREAD

**Issue by ewrayjohnson** [niklasl/ldtr#7]
See: https://www.w3.org/TR/rdf12-schema/#ch_value

**Comment by niklasl** [comment]
Could you provide example data where this error occurs (and how you called ldtr)?

**Comment by ewrayjohnson** [comment]
https://vocab.org/bio/schema.rdf

**Comment by niklasl** [comment]
Thank you! I've addressed this in [a8caa79](https://github.com/niklasl/ldtr/commit/a8caa79d22b570b8b5c0e1bb581e24e33bcecb0b).

**Comment by ewrayjohnson** [comment]
I can confirm this fixes the issue.  When will this be released?

**Comment by niklasl** [comment]
Thanks! I just cut [ldtr 0.6.4](https://www.npmjs.com/package/ldtr) with this fix (and #8).
